language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/MAX30100_Minimal
    - PLATFORMIO_CI_SRC=examples/MAX30100_Debug

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno
